name:                jamaica-web
version:             0.1.0.0
github:              "githubuser/jamaica-web"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jamaica-web#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-compat
- attoparsec
- base-compat
- bytestring
- containers
- directory
- http-api-data
- http-client
- http-media
- http-types
- mtl
- string-conversions
- text
- transformers
- resourcet
- wai
- warp
- monad-logger
- servant
- servant-server
- servant-client
- lucid
- time
- persistent
- persistent-template
- persistent-mysql

library:
  source-dirs: src

executables:
  jamaica-web-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jamaica-web
   

tests:
  jamaica-web-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jamaica-web
